### ISSUE TITLE
7.1.1 and Upload Property Editor in an Archetype

### ISSUE THREAD

**Issue by AussieInSeattle** [imulus/Archetype#114]
Trying to use built-in Umbraco Upload PE with Archetype - I just have a text string + upload for my archetype (originally had a nested archetype with an upload pe).

**When I add some content (text string + a single file upload) and then hit Save + Publish I see this error in the Console:**
TypeError: undefined is not a function
    at initialize (http://innovasian.local/DependencyHandler.axd?s=L3VtYnJhY28vbGliL2pxdWVyeS9…nUvQWN0aW9uTmV3UmVsYXRpb25UeXBlLmpzOw&t=Javascript&cdv=1153965183:1051:148)
    at new fileUploadController (http://innovasian.local/DependencyHandler.axd?s=L3VtYnJhY28vbGliL2pxdWVyeS9…lbnUvQWN0aW9uTmV3UmVsYXRpb25UeXBlLmpzOw&t=Javascript&cdv=1153965183:1054:1)
    at d (http://innovasian.local/umbraco/lib/angular/1.1.5/angular.min.js:28:304)
    at Object.instantiate (http://innovasian.local/umbraco/lib/angular/1.1.5/angular.min.js:28:434)
    at http://innovasian.local/umbraco/lib/angular/1.1.5/angular.min.js:53:326
    at http://innovasian.local/umbraco/lib/angular/1.1.5/angular.min.js:44:274
    at n (http://innovasian.local/umbraco/lib/angular/1.1.5/angular.min.js:7:74)
    at k (http://innovasian.local/umbraco/lib/angular/1.1.5/angular.min.js:44:139)
    at e (http://innovasian.local/umbraco/lib/angular/1.1.5/angular.min.js:40:139)
    at http://innovasian.local/umbraco/lib/angular/1.1.5/angular.min.js:39:205 

An running on 7.1.1

Am using the latest from master as of a few minutes ago.

Regards,
Matt

**Comment by kgiszewski** [comment]
Fixed in #281
