### ISSUE TITLE
Upload Types Broken in 7.2.1

### ISSUE THREAD

**Issue by danwhite85** [imulus/Archetype#246]
I'm starting a fresh Umbraco 7.2.1 site and using Archetype and it seems to be failing with datatypes that upload a file. I've tried both the Image Cropper and the straight Upload. The log shows an error like the following:

    2015-01-07 23:13:49,848 [686] ERROR Archetype.PropertyEditors.ArchetypePropertyEditor+ArchetypePropertyValueEditor - [Thread 688] Value cannot be null.
    Parameter name: input
    System.ArgumentNullException: Value cannot be null.
    Parameter name: input
       at System.Guid.Parse(String input)
       at Archetype.PropertyEditors.ArchetypePropertyEditor.ArchetypePropertyValueEditor.ConvertDbToString(Property property, PropertyType propertyType, IDataTypeService dataTypeService)

**Comment by kjac** [comment]
This issue is not new, I'm afraid - see #114

**Comment by danwhite85** [comment]
Shouldn't #141 have resolved it?

**Comment by kjac** [comment]
It was never merged in - see the last comment :)

**Comment by danwhite85** [comment]
Rats

**Comment by kgiszewski** [comment]
At this time there is no plans to support Upload or Image Cropper types.
